name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Vendor of JDK, here Temurin (AdoptOpenJDK)
          java-version: '21'
          cache: maven  # Enable cache for Maven dependencies

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and run tests
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Run tests separately if needed (optional, if already done in 'install')
      - name: Run tests
        run: mvn test --no-transfer-progress
